### PR TITLE
Backup: jo_backup_save_file() new args

### PR DESCRIPTION
**Pull request by slinga-homebrew**
I need to be able to set the language for saves. Japanese saves have Japanese comments. Without setting the save language to Japanese they do not render correctly in the BIOS.

### CODE REVIEW

**Comment by johannes-fetz** [comment]
I will push a better implementation

**Comment by johannes-fetz** [comment]
jo_backup                           bkp;

    jo_backup_init_file(&bkp);
    bkp.fname = "TEST.BKP";
...
jo_backup_save(&bkp);

**Comment by johannes-fetz** [comment]
You can set language using jo-engine abstraction or native and same for the save date

**Comment by johannes-fetz** [comment]
I deleted jo_backup_save_file_contents_on_partition(). Use jo_backup_save() instead

**Comment by slinga-homebrew** [comment]
Thank you!

**Pull request closed without merging**
