### PR TITLE
Correctly read TGA data with ROW_TOP imagedescriptor

### PR DESCRIPTION
**Pull request by deevus**
Hi Johannes

This fixes an issue with rendering TGA files created by tools where image data is stored top to bottom rather than bottom to top. 

See here: http://www.ryanjuckett.com/programming/parsing-colors-in-a-tga-file/

For brevity:

> ## Parsing the Image Data
> The image data is stored as a large array of color values. Colors are stored row by row, but the order of the rows and the order of the colors within the row are determined by the "image descriptor" (field 5.6 of the file header in the file format documentation). The image descriptor is a single byte value with the bits are numbered as follows:
> 
> ```
> most significant bit       least significant bit
>                 7 6 5 4 3 2 1 0  
> ```
> 
> If bit 5 of the image descriptor is zero, the rows of the image start with the bottom row and end with the top row. Otherwise the rows start with the top row and end with the bottom row.

I also introduced some defines for the TGA header offsets to make the code more readable. 

In my use case I was importing TGAs directly from Krita. If I import the TGA into JoMapEditor first then export, it renders fine. However rendering the file as generated by Krita renders flipped vertically.

### CODE REVIEW

**Comment by deevus** [comment]
To demonstrate the issue, replace `EMY.TGA` in the storyboard demo with this one
[emy.tga.gz](https://github.com/johannes-fetz/joengine/files/3235750/emy.tga.gz)

**Comment by deevus** [comment]
Actually the issue still persists with the example I gave. Back to the drawing board lol

**Comment by deevus** [comment]
Ok there we go. It's been a while since I've done pointer arithmetic

**Comment by johannes-fetz** [comment]
@deevus Thanks for the fix :)

**Pull request merged**
