### PR TITLE
480i 8bit TGA demo

### PR DESCRIPTION
**Pull request by slinga-homebrew**
Modified 8bit TGA demo to run as 480i. It's probably better to move:

```
    // enable 480i
    // makefile needs to set JO_NTSC=1 and JO_480i=1
    #if defined(JO_480i)

    VDP2_CRAOFB = 0x0010 | (VDP2_CRAOFB & 0xFF0F);

    // double the size of the fonts printed by jo_printf()
    slZoomNbg0(32768, 32768);
    #endif
```

from main.c into core.c instead. Please let me know what you think. Credit to fafling and Ponut64 for showing me how to do this.

### CODE REVIEW

**Comment by retrohead** [comment]
Maybe use JO_VDP2_CRAOFB instead of VDP2_CRAOFB ?

**Comment by slinga-homebrew** [comment]
That's good advice. I switched it to JO_VDP2_CRAOFB but it causes issues. The image is no longer displaying correctly. Not sure why.

**Comment by retrohead** [comment]
480i corruption

Had a test, major palette issues going on here. The screenshot shows me trying to force a different palette, which is output in the printf but the 2nd palette doesn't take effect. 

It doesn't seem like we would be able to load more than one palette with this and only indexed TGA's seem to work. I also tried with the hardcoded image demo and the spaceship doesn't display properly and there is some pixel warping going on.

**Comment by johannes-fetz** [comment]
I will check this Pull Request tomorrow :)

**Comment by johannes-fetz** [comment]
I added the code inside core.c in WIP and added PAL support, but I have to continue the implementation, because many demos doesn't work properly. Thx everyone ! :)

**Pull request closed without merging**
